import Config

# Configure your database
config :phoenix_honu_example, PhoenixHonuExample.Repo,
  hostname: "localhost",
  database: "phoenix_honu_example_dev",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :phoenix_honu_example, PhoenixHonuExampleWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "LrkbBWO8zKK+OaElX+HdgKJsq+y61O+XAdOOsOU7Bb+kEWQl44wQAo/eNQ3Uz4Om",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :phoenix_honu_example, PhoenixHonuExampleWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/phoenix_honu_example_web/(live|views)/.*(ex)$",
      ~r"lib/phoenix_honu_example_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :honu, Honu.Storage,
  storage: Honu.Storage.Disk,
  repo: PhoenixHonuExample.Repo,
  root_dir: "storage"

config :honu, HonuWeb.Storage,
  storage: HonuWeb.Storage.Disk,
  secret_key_base: "m+08I7aHnGEeTjfSX8s0reZ/1qmYcwVBgh2bgephQDBTy3yRUlQo8iO0IFkjq6Q1",
  repo: PhoenixHonuExample.Repo,
  service_urls_expire_in: 300
